config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'index', to: 'recipes#index'
  
  #resources :recipes
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy] 
  resources :kinds, except: [:destroy] 

  #recipes/recipe/1 0
  #recipes/recipe/1/ratings/new - post request
  resources :recipes do
    resources :ratings 
  end
end

app/models/kind.rb
class Kind < ApplicationRecord 
    validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 } 

    has_many :recipe_kinds 
    has_many :recipes, through: :recipe_kinds 
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController 
    before_action :require_admin, except: [:show, :index] 

    def index 
        @kinds = Kind.all 
    end

    def show 
        @kind = Kind.find(params[:id])
    end

    def new 
        @kind = Kind.new;
    end

    def create 
        @kind = Kind.new(kind_params)
        if @kind.save 
            flash[:notice] = "Recipe type was created successfully!" 
            redirect_to @kind 
        else
            flash[:alert] = "Recipe type was not created successfully!"
            render 'new'
        end
    end

    private 
    def kind_params 
        params.require(:kind).permit(:name)
    end

    def require_admin 
        if !(helpers.logged_in? && helpers.current_user.admin?)
            flash[:alert] = "Only admins can perform this action." 
            redirect_to kinds_path 
        end
    end

end

app/controllers/kinds_controllers.rb
class KindsController < ApplicationController 
    before_action :require_admin, except: [:show, :index] 

    def index 
        @kinds = Kind.all 
    end

    def show 
        @kind = Kind.find(params[:id])
    end

    def new 
        @kind = Kind.new;
    end

    def create 
        @kind = Kind.new(kind_params)
        if @kind.save 
            flash[:notice] = "Recipe type was created successfully!" 
            redirect_to @kind 
        else
            flash[:alert] = "Recipe type was not created successfully!"
            render 'new'
        end
    end

    private 
    def kind_params 
        params.require(:kind).permit(:name)
    end

    def require_admin 
        if!(helpers.logged_in? && helpers.current_user.admin?)
            flash[:alert] = "Only admins can perform this action." 
            redirect_to kinds_path 
    end

end

app/views/kinds/_kind.html.erb
<%= link_to kind.name, kind_path(kind), class:"badge text-light", id: "badge-item-3", style:"text-decoration: none" %> 

app/views/kinds/index.html.erb
<h1 class="text-center">Recipes by Type</h1>

  <div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @kinds.each do |kind| %>
        <div class="col">
        <div class="card">
            <div class="card-header">
              <%= link_to kind.name, kind_path(kind), class:"text-secondary", style:"font-size: 2rem" %>
            </div>
        </div>
    </div>
    <% end %>
    
</div>
</div>
<br>

app/views/kinds/new.html.erb
<h1 class="text-center">New Recipe Type</h1>

<div style="margin: 0 25%; width: 50%">
  <%= render 'shared/errors', obj: @kind %> 
  
  <%= form_with(model: @kind) do |form| %>
  <div class="mb-3">
    <%= form.label :name, "Name:", class:"form-label", placeholder: "Enter a Recipe Type" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>
  <%= form.submit("Create Recipe Type", class:"btn btn-primary") %> 
  <% end %>
</div>

app/views/kinds/show.html.erb
<h1 class="text-center"><%= @kind.name %></h1>
<div class="text-center"> 
    <%= render 'recipes/recipes', recipes: @kind.recipes %> 
    [<%= link_to 'Return to Recipe Types', kinds_path, class: "text-secondary" %>]
    </div>