config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'index', to: 'recipes#index'
  
  #resources :recipes
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy] 
  resources :kinds, except: [:destroy] 

  #recipes/recipe/1 0
  #recipes/recipe/1/ratings/new - post request
  resources :recipes do
    resources :ratings 
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user 
    has_many :recipe_categories 
    has_many :categories, through: :recipe_categories 

    has_many :recipe_kinds
    has_many :kinds, through: :recipe_kinds 
    
    has_many :ratings
    
    validates :name, presence:true, length: {minimum: 3, maximum: 60} 
    validates :ingredients, presence:true, length: {minimum: 6, maximum: 100}
    validates :instructions, presence:true, length: {minimum: 6}
    validate :image_path_exists,

    def image_path_exists
        require 'open-uri'
        begin
            url = URI.open(image_path)
            errors.add(:image_path, "does not contain image") and return unless url.content_type.starts_with?("image")
        rescue
            errors.add(:image_path, "Invalid URL")
        end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show, :edit, :destroy, :update] 
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:update, :edit, :delete] 


    def show
    end

    def index 
        @recipes = Recipe.all 
    end

    def new
        @recipe = Recipe.new 
    end

    def create 
        @recipe = Recipe.new(recipe_params)
        @recipe.user = helpers.current_user  
        if @recipe.save 
            flash[:notice] = "Recipe saved successfully!"
            redirect_to @recipe
        else 
            render 'new'
        end
    end 
    
    def edit
    end

    def update 
        if @recipe.update(recipe_params)
            flash[:message] = "Update successful!"
            redirect_to @recipe 
        else
            render 'edit'
        end
    end

    def destroy
        flash[:message] = "#{@recipe.name} was deleted successfully!"
        @recipe.destroy
        redirect_to recipes_path 
    end

end 

private 

def set_recipe 
    @recipe = Recipe.find(params[:id])
end

def recipe_params 
    params.require(:recipe).permit(:name, 
                                    :ingredients, 
                                    :instructions, 
                                    :image_path, 
                                    category_ids: [],
                                    kind_ids: [])
    
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div >
  <div class="container text-center"style="margin: 0 25%; width: 50%" id="form-container">
    <%= render 'shared/errors', obj: @recipe, class:"text-align-right" %>
    <%= form_with(model: @recipe, local:true) do |f| %>
      
      <div class="form-group row">
        <div class="col-3">
        <%= f.label :name, class: "col-2 col-form-label text-light"%>
        </div>
        <div class="col-9">
        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name of Recipe" %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <div class="col-3">
        <%= f.label :ingredients, "Ingredients: ", class: "col-2 col-form-label text-light"%><br>
        </div>
        <div class="col-9">
        <%= f.text_area :ingredients, rows: 10, class: "form-control shadow rounded", placeholder: "List Ingredients Here" %>
      </div>
      </div>
      <br>
      <div class="form-group row">
        <div class="col-3">
        <%= f.label :instructions, "Instructions: ", class: "col-2 col-form-label text-light" %><br>
        </div>
        <div class="col-9">
        <%= f.text_area :instructions, rows: 10, class: "form-control shadow rounded", placeholder: "Tell us how to make your recipe" %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <div class="col-3">
        <%= f.label :image_path, "Image URL: ", class: "col-2 col-form-label text-light" %><br>
        </div>
        <div class="col-9">
        <%= f.text_area :image_path, class: "form-control shadow rounded" %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <div class="col-3">
        <%= f.label :category, "Season: ", class: "col-2 col-form-label text-light" %><br>
        </div>
        <div class="col-9">
        <%= f.collection_select(:category_ids, Category.order(:name), :id, :name,
        {prompt: "Select a Season"}, {multiple: true, size: 3, class: "form-control shadow rounded"}) %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <div class="col-3">
        <%= f.label :kind, "Type: ", class: "col-2 col-form-label text-light" %><br>
        </div>
        <div class="col-9">
        <%= f.collection_select(:kind_ids, Kind.order(:name), :id, :name,
        {prompt: "Select a Recipe Type"}, {multiple: true, size: 3, class: "form-select shadow rounded"}) %>
        </div>
      </div>
      <br>
        <%= f.submit(@recipe.new_record? ? "Create Recipe" : "Update Recipe", class:"link btn btn-outline-success") %>
        <% end %>
      </div>
   
  
</div>

app/views/recipes/_recipes.html.erb
<div class="container">
    <div class="row">
        <% recipes.each do |recipe| %>
        <div class="col-md-3 mb-3">
        <div class="card">
            <%= image_tag recipe.image_path, class: "card-img-top" %>
            <div class="card-header">
            by: <%= recipe.user.username if recipe.user  %>
            <div><%= render recipe.categories %></div>
            <div><%= render recipe.kinds %></div>
            <div class="card-body text-center">
                <h5 class="card-title fs-3"><%= link_to "#{recipe.name}", recipe_path(recipe)%></h5>

                <div class="recipe-review-container aria-disabled">
                    <div class="component recipe-ratings">
                        <a href="#" class="add-rating-reviews-link ugc-ratings-link review-stars-container embedded-auth-modal-trigger" data-login-url=""
                                            data-tracking-do-not-follow="true">
                        <span class="rating-star active" aria-hidden="true" data-rating="1">
                            <svg width="24" height="24" viewBox=" 0 0 24 24" role="img" aria-label="1 - Couldn't eat it" xmlns="http://www.w3.org/2000/svg">
                            <path class="rating-star-filled" d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"></path>
                            </svg>
                        </span>
                        <span class="rating-star active" aria-hidden="true" data-rating="1">
                            <svg width="24" height="24" viewBox=" 0 0 24 24" role="img" aria-label="2 - Didn't like it" xmlns="http://www.w3.org/2000/svg">
                            <path class="rating-star-filled" d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"></path>
                            </svg>
                        </span>
                        <span class="rating-star active" aria-hidden="true" data-rating="1">
                            <svg width="24" height="24" viewBox=" 0 0 24 24" role="img" aria-label="3 - It was ok" xmlns="http://www.w3.org/2000/svg">
                            <path class="rating-star-filled" d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"></path>
                            </svg>
                        </span>
                        <span class="rating-star active" aria-hidden="true" data-rating="1">
                            <svg width="24" height="24" viewBox=" 0 0 24 24" role="img" aria-label="4 - Like it" xmlns="http://www.w3.org/2000/svg">
                            <path class="rating-star-filled" d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"></path>
                            </svg>
                        </span>
                        <span class="rating-star active" aria-hidden="true" data-rating="1">
                            <svg width="24" height="24" viewBox=" 0 0 24 24" role="img" aria-label="5 - Loved it" xmlns="http://www.w3.org/2000/svg">
                            <path class="rating-star-filled" d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"></path>
                            </svg>
                        </span>

                        </a>
                    </div>
                </div>

                <p class="card-text">Ingredients: <%= recipe.ingredients %></p>
                <p class="card-text">Instructions: <%= recipe.instructions %></p>
                <%= link_to 'Show', recipe_path(recipe), class:"link btn btn-outline-warning" %>
                <% if logged_in? && (recipe.user == current_user || current_user.admin) %>
                    <%= link_to 'Edit', edit_recipe_path(recipe), class:"link btn btn-outline-success" %>
                    <%= link_to 'Delete', recipe_path(recipe), method: :delete, class:"link btn btn-outline-dark" %>
                <% end %> 
            </div>
            <div class="card-footer fs-6">
                <small class="text-muted">Updated <%= time_ago_in_words(recipe.updated_at) %></small>
            </div>
            </div>
        </div>
    </div>
    <% end %>
    
</div>
</div>
<br>

app/views/recipes/edit.html.erb
<div class="text-center">
    <h1>Edit <%= @recipe.name %> </h1>
    <%= render 'form' %>
    <br>
    [<%= link_to 'Cancel and go back to the Recipe Listings', recipes_path, class: "text-secondary" %>]
</div>

app/views/recipes/index.html.erb
<h1 style="font-size: 5rem; text-align:center;" id="library">Recipe Library</h1>
<%= render 'recipes', recipes: @recipes %>

app/views/recipes/new.html.erb
<div class="text-center">
    <h1>Create a new recipe!</h1>
    <%= render 'form' %>
    <br>
    [<%= link_to 'Cancel and go back to the Recipe Listings', recipes_path, class: "text-secondary" %>]
</div>

app/views/recipes/show.html.erb
<h1 class="text-center">From the Recipe Library</h1>

<div class="card" style="margin: 0 25%; width: 50%">
    <img src="<%= @recipe.image_path%>" class="card-img-top, img-thumbnail" alt="...">
    <div class="card-body">
      <h5 class="card-title text-center"><strong><%= @recipe.name %></strong></h5>
    </div>
    <div class="card-header text-center">
      <%= @recipe.user.username if @recipe.user %>
      <% if @recipe.categories.any? %>
        <div><%= render @recipe.categories %> </div>
      <% end %>
      <% if @recipe.kinds.any? %>
      <div><%= render @recipe.kinds %></div>
      <% end %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>Ingredients: </strong><%= @recipe.ingredients %></li>
      <li class="list-group-item"><strong>Instructions: </strong><%= @recipe.instructions %></li>
    </ul>
    <div class="card-body text-center">
     
        <%= link_to 'Return', recipes_path, class:"link btn btn-outline-warning"%>
        <% if logged_in? && (@recipe.user == current_user || current_user.admin) %>
          <%= link_to 'Edit', edit_recipe_path(@recipe), class:"link btn btn-outline-success" %>
        <%= button_to 'Delete', recipe_path(@recipe), method: :delete, data: {confrim: "Are you sure you want to delete?"}, class:"link btn btn-outline-dark ", form: {style: "display: inline-block"} %>
        <% end %>
  
    </div>
  </div>
  </div>
  <br>
  