config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'index', to: 'recipes#index'
  
  #resources :recipes
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy] 
  resources :kinds, except: [:destroy] 

  #recipes/recipe/1 0
  #recipes/recipe/1/ratings/new - post request
  resources :recipes do
    resources :ratings 
  end
end

app/models/category.rb
class Category < ApplicationRecord 
    has_many :recipe_categories 
    has_many :recipes, through: :recipe_categories 
    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25 }
    # validate :image_path_exists
    
    # def image_path_exists
    #     require 'open-uri'
    #     begin
    #         url = URI.open(image_path)
    #         errors.add(:image_path, "does not contain image") and return unless url.content_type.starts_with?("image")
    #     rescue
    #         errors.add(:image_path, "Invalid URL")
    #     end
    # end

    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
    before_action :require_admin, except: [:show, :index, :edit] 

    def index 
        @categories = Category.all
    end

    def show 
        @category = Category.find(params[:id]) 
    end

    def new 
        @category = Category.new 
    end 

    def edit 

    end

    def create 
        @category = Category.new(category_params)
        if @category.save 
            flash[:notice] = "Category creation was successful!" 
            redirect_to @category 
        else
            flash[:alert] = "Category was not created successfully."
            render 'new'
        end
    end

    private 
    def category_params 
        params.require(:category).permit(:name) 
    end

    def require_admin 
        if !(helpers.logged_in? && helpers.current_user.admin?)
            flash[:alert] = "Only admins can perform this action!"
            redirect_to categories_path 
        end
    end

end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge text-light", id: "badge-item-2", style:"text-decoration: none" %> 

app/views/categories/index.html.erb
<h1 class="text-center">Recipes by Season</h1>
  <div class="container">
    <div class="row">
      <% @categories.each do |category| %>
        <div class="col-md-3 mb-3">
        <div class="card">
           <%= image_tag category.image_path, class: "card-img-top" %>
            <div class="card-header">
              <%= link_to category.name, category_path(category), class:"text-secondary", style:"font-size: 2rem" %>
            </div>
        </div>
    </div>
    <% end %>
    
</div>
</div>
<br>

app/views/categories/new.html.erb
<div >
    <h1 class="text-center">Create a New Category</h1>

    <div class="container text-center"style="margin: 0 25%; width: 50%" id="form-container">
      <%= render 'shared/errors', obj: @category, class:"text-align-right" %>
      <%= form_with(model: @category) do |f| %>
        
        <div class="form-group row">
          <%= f.label :name, "Category Name", class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a Category" %>
          </div>
        </div>
        <br>
        <div class="form-group row">
          <div class="col-3">
          <%= f.label :image_path, "Image URL: ", class: "col-2 col-form-label text-light" %><br>
          </div>
          <div class="col-9">
          <%= f.text_area :image_path, class: "form-control shadow rounded" %>
          </div>
        </div>
        <br>
          <%= f.submit("Create Category" , class:"link btn btn-outline-success") %>
    </div>   
    <% end %>
  </div>

app/views/categories/show.html.erb
<h1 class="text-center"><%= @category.name %> Recipes</h1>
<div class="text-center"> 
<%= render 'recipes/recipes', recipes: @category.recipes %> 
[<%= link_to 'Return to Seasonal Listings', categories_path, class: "text-secondary" %>]
</div>