config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'index', to: 'recipes#index'
  
  #resources :recipes
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy] 
  resources :kinds, except: [:destroy] 

  #recipes/recipe/1 0
  #recipes/recipe/1/ratings/new - post request
  resources :recipes do
    resources :ratings 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord 
    has_many :recipe_categories 
    has_many :recipes, through: :recipe_categories 
    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25 }
    # validate :image_path_exists
    
    # def image_path_exists
    #     require 'open-uri'
    #     begin
    #         url = URI.open(image_path)
    #         errors.add(:image_path, "does not contain image") and return unless url.content_type.starts_with?("image")
    #     rescue
    #         errors.add(:image_path, "Invalid URL")
    #     end
    # end

    
end

app/models/kind.rb
class Kind < ApplicationRecord 
    validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 } 

    has_many :recipe_kinds 
    has_many :recipes, through: :recipe_kinds 
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ApplicationRecord 
    belongs_to :recipe
    belongs_to :user
    belongs_to :rating 
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user 
    has_many :recipe_categories 
    has_many :categories, through: :recipe_categories 

    has_many :recipe_kinds
    has_many :kinds, through: :recipe_kinds 
    
    has_many :ratings
    
    validates :name, presence:true, length: {minimum: 3, maximum: 60} 
    validates :ingredients, presence:true, length: {minimum: 6, maximum: 100}
    validates :instructions, presence:true, length: {minimum: 6}
    validate :image_path_exists,

    def image_path_exists
        require 'open-uri'
        begin
            url = URI.open(image_path)
            errors.add(:image_path, "does not contain image") and return unless url.content_type.starts_with?("image")
        rescue
            errors.add(:image_path, "Invalid URL")
        end
    end
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord 
    belongs_to :recipe
    belongs_to :category 
end

app/models/recipe_kind.rb
class RecipeKind < ApplicationRecord 
    belongs_to :recipe
    belongs_to :kind 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    has_many :recipes, dependent: :destroy
    has_many :ratings 

    validates :username, uniqueness: true, presence: true, length: { minimum: 3, maximum: 25 }
    validates :email, uniqueness: true, presence: true, length: { minimum: 5, maximum: 25 }, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController 
    before_action :require_admin, except: [:show, :index] 

    def index 
        @kinds = Kind.all 
    end

    def show 
        @kind = Kind.find(params[:id])
    end

    def new 
        @kind = Kind.new;
    end

    def create 
        @kind = Kind.new(kind_params)
        if @kind.save 
            flash[:notice] = "Recipe type was created successfully!" 
            redirect_to @kind 
        else
            flash[:alert] = "Recipe type was not created successfully!"
            render 'new'
        end
    end

    private 
    def kind_params 
        params.require(:kind).permit(:name)
    end

    def require_admin 
        if !(helpers.logged_in? && helpers.current_user.admin?)
            flash[:alert] = "Only admins can perform this action." 
            redirect_to kinds_path 
        end
    end

end

app/controllers/kinds_controllers.rb
class KindsController < ApplicationController 
    before_action :require_admin, except: [:show, :index] 

    def index 
        @kinds = Kind.all 
    end

    def show 
        @kind = Kind.find(params[:id])
    end

    def new 
        @kind = Kind.new;
    end

    def create 
        @kind = Kind.new(kind_params)
        if @kind.save 
            flash[:notice] = "Recipe type was created successfully!" 
            redirect_to @kind 
        else
            flash[:alert] = "Recipe type was not created successfully!"
            render 'new'
        end
    end

    private 
    def kind_params 
        params.require(:kind).permit(:name)
    end

    def require_admin 
        if!(helpers.logged_in? && helpers.current_user.admin?)
            flash[:alert] = "Only admins can perform this action." 
            redirect_to kinds_path 
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to recipes_path if helpers.logged_in? 
    end

    def about
        
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, :require_same_user, only: [:edit, :update, :destroy] 

    def index 
        @users = User.all
    end

    def show 
        
    end

    def new 
        @user = User.new 
    end

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            flash[:notice] = "Welcome #{@user.username} to Seasonal Plate, you have successfully signed up!"
            redirect_to recipes_path 
        else
            render 'new' 
        end
    end

    def edit 
        
    end

    def update 
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated."
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy 
        @user.destroy 
        session[:user_id] = nil if @user == helpers.current_user
        flash[:notice] = "Account and all information related to your account has been successfully deleted!" 
        redirect_to root_path 
    end

    private
        def user_params 
            params.require(:user).permit(:username, :email, :password) 
        end

        def set_user 
            @user = User.find(params[:id])
        end

        
        
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user 
        @current_user ||= User.find(session[:user_id]) if session[:user_id] 

    end

    def logged_in? 
        !!current_user
    end
    
end

app/helpers/pages_helper.rb
module PagesHelper
    def get_eight_recipes
        if Recipe.all.count == 0
            return []
        elseif Recipe.all.count <9
            return Recipe.all.count.times.map{Recipe.all[Random.rand(Recipe.count)]}
        else
            return 8.times.map {Recipe.all[Random.rand(Recipe.count)]}
        end
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
    <div class="container text-center">
      <span class="text-white"><small>Copyright &copy; <%= link_to "Hannah Hammonds", "https://triple-h-portfolio.herokuapp.com/", class: "text-white" %> </small></span>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container text-align-start">
<% flash.each do |name, message| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
      <%= link_to "Seasonal Plate", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Recipes
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "About", about_path, class: "dropdown-item" %></li>
              <li><%= link_to "Recipes", recipes_path, class: "dropdown-item" %></li>
              <li><%= link_to "Recipes by Season", categories_path, class: "dropdown-item" %></li>
              <li><%= link_to "Recipes by Type", kinds_path, class: "dropdown-item" %></li>
              <li><%= link_to "Recipe Contributors", users_path, class: "dropdown-item" %></li>
              <% if logged_in? %>
                <li><%= link_to "Create New Recipe", new_recipe_path, class: "dropdown-item" %></li>
              <% end %> 
              <% if logged_in? && current_user.admin? %>
              <li>
                <%= link_to "Create New Recipe Type", new_kind_path, class: "dropdown-item" %>
              </li>
              <% end %> 
            </ul>
          </li>

          
          <% if logged_in? %>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
             > <%= "(Admin)" if @current_user.admin? %> <%= @current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "View Profile", user_path(@current_user),
                class:"dropdown-item" %>
              </li>
              <li>
                <%= link_to "Edit Profile", edit_user_path(@current_user), class:
                "dropdown-item"%>
              </li>
              <li>
                <%= button_to "Delete Profile", user_path(@current_user), class:
                "dropdown-item"%>
              </li>
            </ul>
          </li>
          <% end %>

          <% if logged_in? %>
          <li class="nav-item"><%= button_to "Log Out", logout_path, class: "nav-link button-link", method: :delete %>
          </li> 
          <% else %>
          <li class="nav-item"><%= link_to "Log In", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "nav-link" %>
          </li>
          <% end %>

        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-light" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content"></div> 
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>  
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <div class="center" >
      <div class="p-5 rounded-lg m-5" id="about-container">
        <div>
          <h1 class="display-6 text-center mt-50">About Seasonal Plate</h1>
          <hr class="my-4">
      </div>
      </div>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<div class="container">
  <div class="center text-orange" >
    <div class="p-5 rounded-lg m-5" id="home-container">
      <div>
        <h1 class="display-4 text-center mt-50">Welcome to the Seasonal Plate</h1>
        <h2 class="lead text text-center">Find recipes using fresh ingredients by season or recipe typeand create your own. 
          <br> Sign up today!</h2>
        <hr class="my-4">
        <br>
        <br>
        <div class="text-center">
          <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg text-center" %>
        </div>
    </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
        <% get_eight_recipes.each do |recipe| %>
        <div class="col-md-3 mb-3">
        <div class="card">
            <%= image_tag recipe.image_path, class: "card-img-top" %>
            
            <div class="card-body text-center">
                <h5 class="card-title"><%= link_to "#{recipe.name}", recipe_path(recipe)%></h5>
            </div>
            <div class="card-footer">
                <small class="text-muted">Updated <%= time_ago_in_words(recipe.updated_at) %></small>
            </div>
        </div>
    </div>
    <% end %>
</div>
</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissable fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class %> from being saved!</h4>
    <p class="text-align-start">
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>